export const NEW_MESSAGE = 'NEW_MESSAGE'
export const SET_ID = 'SET_ID'
export const REMOVE_ID = 'REMOVE_ID'
export const REMOVE_LAST_MESSAGE = 'REMOVE_LAST_MESSAGE'
export const SET_NICK = 'SET_NICK'
export const SET_FRIEND_NICK = 'SET_FRIEND_NICK'
export const SET_TYPING = 'SET_TYPING'
export const RESET_TYPING = 'RESET_TYPING'
export const FADE_LAST = 'FADE_LAST'

export const CMD_OOPS = '/oops'
export const CMD_NICK = '/nick'
export const CMD_FADE_LAST = '/fadelast'
export const CMD_TYPING = '/typing'
export const CMD_NOT_TYPING = '/!typing'
export const CMD_COUNTDOWN = '/countdown'
export const CMD_HIGHLIGHT = '/highlight'
export const CMD_THINK = '/think'
